"""empty message

Revision ID: 31244da9ec0f
Revises: 5ce61e05d123
Create Date: 2023-12-26 23:00:53.427762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31244da9ec0f'
down_revision = '5ce61e05d123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.alter_column('certificate',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=400),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=400),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('img',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('certificate',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
